services:
  backend:
    image: aashu123/foodsite-backend:latest
    container_name: backendCo
    ports:
      - "8001:8000"
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pip install -r requirements.txt && gunicorn --bind 0.0.0.0:8000 foodsite.wsgi:application"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "90:80"
    volumes:
      - ./conf.d/dockerdjango.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: always