name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: SSH into EC2 and deploy
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          ssh -i ec2_key.pem -p ${{ secrets.EC2_SSH_PORT }} -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Installing Python 3.12 and dependencies..."
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt update
            sudo apt install -y python3.12 python3.12-venv python3.12-dev python3-pip libpq-dev build-essential git

            REPO_URL="https://${PAT_TOKEN}@github.com/asha-sharma124/CuisineBackend.git"
            PROJECT_DIR="${{ secrets.EC2_PROJECT_DIR }}"

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "Cloning repository..."
              git clone $REPO_URL $PROJECT_DIR
            else
              echo "Pulling latest changes..."
              cd $PROJECT_DIR
              git reset --hard
              git pull $REPO_URL
            fi

            cd $PROJECT_DIR

            echo "Removing old virtual environment if exists..."
            rm -rf venv

            echo "Creating new virtual environment with Python 3.12..."
            python3.12 -m venv venv

            echo "Activating virtual environment..."
            source venv/bin/activate

            echo "Upgrading pip, setuptools, and wheel..."
            venv/bin/pip install --upgrade pip setuptools wheel

            echo "Uninstalling existing psycopg or psycopg2 (if any)..."
            venv/bin/pip show psycopg && venv/bin/pip uninstall -y psycopg || true
            venv/bin/pip show psycopg2 && venv/bin/pip uninstall -y psycopg2 psycopg2-binary || true

            echo "Installing psycopg with binary extras..."
            venv/bin/pip install "psycopg[binary]"

            echo "Installing project dependencies from requirements.txt..."
            venv/bin/pip install -r requirements.txt

            echo "Verifying psycopg import..."
            venv/bin/python -c "import psycopg" || { echo 'ERROR: psycopg module not found'; exit 1; }

            echo "Running Django database migrations..."
            venv/bin/python manage.py migrate

            echo "Exporting DJANGO_SETTINGS_MODULE..."
            export DJANGO_SETTINGS_MODULE=foodsite.settings

            echo "Restarting Django service..."
            sudo systemctl daemon-reload
            sudo systemctl restart foodsite

            echo "✅ Deployment completed successfully!"
          EOF
