name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Triggers on push to 'staging' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Sync project to EC2
        run: |
          rsync -avz -e "ssh -i ec2_key.pem -p ${{ secrets.EC2_SSH_PORT }} -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PROJECT_DIR }}

      - name: SSH into EC2 and deploy
        run: |
           ssh -i ec2_key.pem -p ${{ secrets.EC2_SSH_PORT }} -o StrictHostKeyChecking=no \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              sudo apt update
              sudo apt install python3 python3-venv python3-pip -y
              cd ${{ secrets.EC2_PROJECT_DIR }}
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              python manage.py migrate
              python manage.py collectstatic --noinput
              sudo systemctl daemon-reload
              sudo systemctl restart foodsite
            EOF
